apiVersion : apps/v1
kind : Deployment
metadata :
  name : java-deployment
  labels :
   app : javawebcalculator
  spec :
   replicas : 1
   selector :
    matchLabels :
     app : javawebcalculator
  template:
    metadata :
     labels :
       app : javawebcalculator
    spec :
     containers :
     - name : javawebcaculator
       image : rajputsonalika571/javawebcalculator
       ports:
       - containerPort : 8085
