apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebcalculator-deployment
  labels:
    app: javawebcalculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebcalculator
  template:
    metadata:
      labels:
        app: javawebcalculator
    spec:
      containers:
      - name: javawebcalculator
        image: rajputsonalika571/javawebcalculator:latest
        ports:
        - containerPort: 8085
