apiVersion: v1
kind: Service
metadata:
  name: javawebcalculator-service
spec:
  selector:
    app: javawebcalculator
  ports:
    - protocol: TCP
      port: 80  # Exposed port on the Service
      targetPort: 8085  # Port inside the container (Tomcat)
  type: LoadBalancer  # External acces
